services:
  tracker-ui:
    image: tracker-ui:latest
    build:
      context: ./tracker-ui
    ports:
      - "3000:3000"
  tracker-server:
    image: tracker-server:latest
    build:
      context: ./tracker-server
    ports:
      - "5000:5000"