CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "password" varchar,
  "email" varchar UNIQUE NOT NULL,
  "phone_number" varchar
);

CREATE TABLE "habit" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "active" boolean NOT NULL DEFAULT true,
  "classification" varchar,
  "user_id" bigint
);

CREATE TABLE "habit_entry" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_date" TIMESTAMP with time zone not null DEFAULT now(),
  "note" varchar,
  "status" varchar,
  "habit_id" bigint,
  "goal_id" bigint
);

CREATE TABLE "goal" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "frequency_num" integer,
  "frequency_type" varchar,
  "habit_id" bigint
);

CREATE TABLE "mood" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "mood_entry" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_date" TIMESTAMP with time zone not null DEFAULT now(),
  "note" varchar,
  "mood_id" bigint,
  "user_id" bigint
);

CREATE TABLE "habit_mood" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mood_id" bigint,
  "habit_id" bigint
);

ALTER TABLE "habit" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "habit_entry" ADD FOREIGN KEY ("habit_id") REFERENCES "habit" ("id");

ALTER TABLE "habit_entry" ADD FOREIGN KEY ("goal_id") REFERENCES "goal" ("id");

ALTER TABLE "goal" ADD FOREIGN KEY ("habit_id") REFERENCES "habit" ("id");

ALTER TABLE "mood_entry" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "mood_entry" ADD FOREIGN KEY ("mood_id") REFERENCES "mood" ("id");

ALTER TABLE "habit_mood" ADD FOREIGN KEY ("mood_id") REFERENCES "mood" ("id");

ALTER TABLE "habit_mood" ADD FOREIGN KEY ("habit_id") REFERENCES "habit" ("id");
