/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CreateUser: typeof import('./components/User/CreateUser.vue')['default']
    HabitCreate: typeof import('./components/Habit/HabitCreate.vue')['default']
    HabitList: typeof import('./components/Habit/HabitList.vue')['default']
    HelloWorld: typeof import('./components/Home.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    HomeCard: typeof import('./components/HomeCard.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserLogin: typeof import('./components/User/UserLogin.vue')['default']
  }
}
